class StaticDataService {
  /** Dummy Api's **/
  getCountryCodeDetails() {
    return new Promise(function (resolve, reject) {
      resolve({
        status: 200,
        data: [
          {
            id: 1,
            flag: "https://www.countryflags.io/af/flat/64.png",
            code: "+93",
            display: "+93 (Afghanistan)",
          },
          {
            id: 2,
            flag: "https://www.countryflags.io/al/flat/64.png",
            code: "+355",
            display: "+355 (Albania)",
          },
          {
            id: 3,
            flag: "https://www.countryflags.io/dz/flat/64.png",
            code: "+213",
            display: "+213 (Algeria)",
          },
          {
            id: 4,
            flag: "https://www.countryflags.io/as/flat/64.png",
            code: "+1684",
            display: "+1684 (American Samoa)",
          },
          {
            id: 5,
            flag: "https://www.countryflags.io/ad/flat/64.png",
            code: "+376",
            display: "+376 (Andorra)",
          },
          {
            id: 6,
            flag: "https://www.countryflags.io/ao/flat/64.png",
            code: "+244",
            display: "+244 (Angola)",
          },
          {
            id: 7,
            flag: "https://www.countryflags.io/ai/flat/64.png",
            code: "+1264",
            display: "+1264 (Anguilla)",
          },
          {
            id: 8,
            flag: "https://www.countryflags.io/aq/flat/64.png",
            code: "+672",
            display: "+672 (Antarctica)",
          },
          {
            id: 9,
            flag: "https://www.countryflags.io/ag/flat/64.png",
            code: "+1268",
            display: "+1268 (Antigua and Barbuda)",
          },
          {
            id: 10,
            flag: "https://www.countryflags.io/ar/flat/64.png",
            code: "+54",
            display: "+54 (Argentina)",
          },
          {
            id: 11,
            flag: "https://www.countryflags.io/am/flat/64.png",
            code: "+374",
            display: "+374 (Armenia)",
          },
          {
            id: 12,
            flag: "https://www.countryflags.io/aw/flat/64.png",
            code: "+297",
            display: "+297 (Aruba)",
          },
          {
            id: 13,
            flag: "https://www.countryflags.io/au/flat/64.png",
            code: "+61",
            display: "+61 (Australia)",
          },
          {
            id: 14,
            flag: "https://www.countryflags.io/at/flat/64.png",
            code: "+43",
            display: "+43 (Austria)",
          },
          {
            id: 15,
            flag: "https://www.countryflags.io/az/flat/64.png",
            code: "+994",
            display: "+994 (Azerbaijan)",
          },
          {
            id: 16,
            flag: "https://www.countryflags.io/bs/flat/64.png",
            code: "+1242",
            display: "+1242 (Bahamas)",
          },
          {
            id: 17,
            flag: "https://www.countryflags.io/bh/flat/64.png",
            code: "+973",
            display: "+973 (Bahrain)",
          },
          {
            id: 18,
            flag: "https://www.countryflags.io/bd/flat/64.png",
            code: "+880",
            display: "+880 (Bangladesh)",
          },
          {
            id: 19,
            flag: "https://www.countryflags.io/bb/flat/64.png",
            code: "+1246",
            display: "+1246 (Barbados)",
          },
          {
            id: 20,
            flag: "https://www.countryflags.io/by/flat/64.png",
            code: "+375",
            display: "+375 (Belarus)",
          },
          {
            id: 21,
            flag: "https://www.countryflags.io/be/flat/64.png",
            code: "+32",
            display: "+32 (Belgium)",
          },
          {
            id: 22,
            flag: "https://www.countryflags.io/bz/flat/64.png",
            code: "+501",
            display: "+501 (Belize)",
          },
          {
            id: 23,
            flag: "https://www.countryflags.io/bj/flat/64.png",
            code: "+229",
            display: "+229 (Benin)",
          },
          {
            id: 24,
            flag: "https://www.countryflags.io/bm/flat/64.png",
            code: "+1441",
            display: "+1441 (Bermuda)",
          },
          {
            id: 25,
            flag: "https://www.countryflags.io/bt/flat/64.png",
            code: "+975",
            display: "+975 (Bhutan)",
          },
          {
            id: 26,
            flag: "https://www.countryflags.io/bo/flat/64.png",
            code: "+591",
            display: "+591 (Bolivia)",
          },
          {
            id: 27,
            flag: "https://www.countryflags.io/ba/flat/64.png",
            code: "+387",
            display: "+387 (Bosnia and Herzegovina)",
          },
          {
            id: 28,
            flag: "https://www.countryflags.io/bw/flat/64.png",
            code: "+267",
            display: "+267 (Botswana)",
          },
          {
            id: 29,
            flag: "https://www.countryflags.io/br/flat/64.png",
            code: "+55",
            display: "+55 (Brazil)",
          },
          {
            id: 30,
            flag: "https://www.countryflags.io/io/flat/64.png",
            code: "+246",
            display: "+246 (British Indian Ocean Territory)",
          },
          {
            id: 31,
            flag: "https://www.countryflags.io/vg/flat/64.png",
            code: "+1284",
            display: "+1284 (British Virgin Islands)",
          },
          {
            id: 32,
            flag: "https://www.countryflags.io/bn/flat/64.png",
            code: "+673",
            display: "+673 (Brunei)",
          },
          {
            id: 33,
            flag: "https://www.countryflags.io/bg/flat/64.png",
            code: "+359",
            display: "+359 (Bulgaria)",
          },
          {
            id: 34,
            flag: "https://www.countryflags.io/bf/flat/64.png",
            code: "+226",
            display: "+226 (Burkina Faso)",
          },
          {
            id: 35,
            flag: "https://www.countryflags.io/bi/flat/64.png",
            code: "+257",
            display: "+257 (Burundi)",
          },
          {
            id: 36,
            flag: "https://www.countryflags.io/kh/flat/64.png",
            code: "+855",
            display: "+855 (Cambodia)",
          },
          {
            id: 37,
            flag: "https://www.countryflags.io/cm/flat/64.png",
            code: "+237",
            display: "+237 (Cameroon)",
          },
          {
            id: 38,
            flag: "https://www.countryflags.io/ca/flat/64.png",
            code: "+1",
            display: "+1 (Canada)",
          },
          {
            id: 39,
            flag: "https://www.countryflags.io/cv/flat/64.png",
            code: "+238",
            display: "+238 (Cape Verde)",
          },
          {
            id: 40,
            flag: "https://www.countryflags.io/ky/flat/64.png",
            code: "+1345",
            display: "+1345 (Cayman Islands)",
          },
          {
            id: 41,
            flag: "https://www.countryflags.io/cf/flat/64.png",
            code: "+236",
            display: "+236 (Central African Republic)",
          },
          {
            id: 42,
            flag: "https://www.countryflags.io/td/flat/64.png",
            code: "+235",
            display: "+235 (Chad)",
          },
          {
            id: 43,
            flag: "https://www.countryflags.io/cl/flat/64.png",
            code: "+56",
            display: "+56 (Chile)",
          },
          {
            id: 44,
            flag: "https://www.countryflags.io/cn/flat/64.png",
            code: "+86",
            display: "+86 (China)",
          },
          {
            id: 45,
            flag: "https://www.countryflags.io/cx/flat/64.png",
            code: "+61",
            display: "+61 (Christmas Island)",
          },
          {
            id: 46,
            flag: "https://www.countryflags.io/cc/flat/64.png",
            code: "+61",
            display: "+61 (Cocos Islands)",
          },
          {
            id: 47,
            flag: "https://www.countryflags.io/co/flat/64.png",
            code: "+57",
            display: "+57 (Colombia)",
          },
          {
            id: 48,
            flag: "https://www.countryflags.io/km/flat/64.png",
            code: "+269",
            display: "+269 (Comoros)",
          },
          {
            id: 49,
            flag: "https://www.countryflags.io/ck/flat/64.png",
            code: "+682",
            display: "+682 (Cook Islands)",
          },
          {
            id: 50,
            flag: "https://www.countryflags.io/cr/flat/64.png",
            code: "+506",
            display: "+506 (Costa Rica)",
          },
          {
            id: 51,
            flag: "https://www.countryflags.io/hr/flat/64.png",
            code: "+385",
            display: "+385 (Croatia)",
          },
          {
            id: 52,
            flag: "https://www.countryflags.io/cu/flat/64.png",
            code: "+53",
            display: "+53 (Cuba)",
          },
          {
            id: 53,
            flag: "https://www.countryflags.io/cw/flat/64.png",
            code: "+599",
            display: "+599 (Curacao)",
          },
          {
            id: 54,
            flag: "https://www.countryflags.io/cy/flat/64.png",
            code: "+357",
            display: "+357 (Cyprus)",
          },
          {
            id: 55,
            flag: "https://www.countryflags.io/cz/flat/64.png",
            code: "+420",
            display: "+420 (Czech Republic)",
          },
          {
            id: 56,
            flag: "https://www.countryflags.io/cd/flat/64.png",
            code: "+243",
            display: "+243 (Democratic Republic of the Congo)",
          },
          {
            id: 57,
            flag: "https://www.countryflags.io/dk/flat/64.png",
            code: "+45",
            display: "+45 (Denmark)",
          },
          {
            id: 58,
            flag: "https://www.countryflags.io/dj/flat/64.png",
            code: "+253",
            display: "+253 (Djibouti)",
          },
          {
            id: 59,
            flag: "https://www.countryflags.io/dm/flat/64.png",
            code: "+1767",
            display: "+1767 (Dominica)",
          },
          {
            id: 60,
            flag: "https://www.countryflags.io/do/flat/64.png",
            code: "+1809, 1829, 1849",
            display: "+1809, 1829, 1849 (Dominican Republic)",
          },
          {
            id: 61,
            flag: "https://www.countryflags.io/tl/flat/64.png",
            code: "+670",
            display: "+670 (East Timor)",
          },
          {
            id: 62,
            flag: "https://www.countryflags.io/ec/flat/64.png",
            code: "+593",
            display: "+593 (Ecuador)",
          },
          {
            id: 63,
            flag: "https://www.countryflags.io/eg/flat/64.png",
            code: "+20",
            display: "+20 (Egypt)",
          },
          {
            id: 64,
            flag: "https://www.countryflags.io/sv/flat/64.png",
            code: "+503",
            display: "+503 (El Salvador)",
          },
          {
            id: 65,
            flag: "https://www.countryflags.io/gq/flat/64.png",
            code: "+240",
            display: "+240 (Equatorial Guinea)",
          },
          {
            id: 66,
            flag: "https://www.countryflags.io/er/flat/64.png",
            code: "+291",
            display: "+291 (Eritrea)",
          },
          {
            id: 67,
            flag: "https://www.countryflags.io/ee/flat/64.png",
            code: "+372",
            display: "+372 (Estonia)",
          },
          {
            id: 68,
            flag: "https://www.countryflags.io/et/flat/64.png",
            code: "+251",
            display: "+251 (Ethiopia)",
          },
          {
            id: 69,
            flag: "https://www.countryflags.io/fk/flat/64.png",
            code: "+500",
            display: "+500 (Falkland Islands)",
          },
          {
            id: 70,
            flag: "https://www.countryflags.io/fo/flat/64.png",
            code: "+298",
            display: "+298 (Faroe Islands)",
          },
          {
            id: 71,
            flag: "https://www.countryflags.io/fj/flat/64.png",
            code: "+679",
            display: "+679 (Fiji)",
          },
          {
            id: 72,
            flag: "https://www.countryflags.io/fi/flat/64.png",
            code: "+358",
            display: "+358 (Finland)",
          },
          {
            id: 73,
            flag: "https://www.countryflags.io/fr/flat/64.png",
            code: "+33",
            display: "+33 (France)",
          },
          {
            id: 74,
            flag: "https://www.countryflags.io/pf/flat/64.png",
            code: "+689",
            display: "+689 (French Polynesia)",
          },
          {
            id: 75,
            flag: "https://www.countryflags.io/ga/flat/64.png",
            code: "+241",
            display: "+241 (Gabon)",
          },
          {
            id: 76,
            flag: "https://www.countryflags.io/gm/flat/64.png",
            code: "+220",
            display: "+220 (Gambia)",
          },
          {
            id: 77,
            flag: "https://www.countryflags.io/ge/flat/64.png",
            code: "+995",
            display: "+995 (Georgia)",
          },
          {
            id: 78,
            flag: "https://www.countryflags.io/de/flat/64.png",
            code: "+49",
            display: "+49 (Germany)",
          },
          {
            id: 79,
            flag: "https://www.countryflags.io/gh/flat/64.png",
            code: "+233",
            display: "+233 (Ghana)",
          },
          {
            id: 80,
            flag: "https://www.countryflags.io/gi/flat/64.png",
            code: "+350",
            display: "+350 (Gibraltar)",
          },
          {
            id: 81,
            flag: "https://www.countryflags.io/gr/flat/64.png",
            code: "+30",
            display: "+30 (Greece)",
          },
          {
            id: 82,
            flag: "https://www.countryflags.io/gl/flat/64.png",
            code: "+299",
            display: "+299 (Greenland)",
          },
          {
            id: 83,
            flag: "https://www.countryflags.io/gd/flat/64.png",
            code: "+1473",
            display: "+1473 (Grenada)",
          },
          {
            id: 84,
            flag: "https://www.countryflags.io/gu/flat/64.png",
            code: "+1671",
            display: "+1671 (Guam)",
          },
          {
            id: 85,
            flag: "https://www.countryflags.io/gt/flat/64.png",
            code: "+502",
            display: "+502 (Guatemala)",
          },
          {
            id: 86,
            flag: "https://www.countryflags.io/gg/flat/64.png",
            code: "+441481",
            display: "+441481 (Guernsey)",
          },
          {
            id: 87,
            flag: "https://www.countryflags.io/gn/flat/64.png",
            code: "+224",
            display: "+224 (Guinea)",
          },
          {
            id: 88,
            flag: "https://www.countryflags.io/gw/flat/64.png",
            code: "+245",
            display: "+245 (Guinea-Bissau)",
          },
          {
            id: 89,
            flag: "https://www.countryflags.io/gy/flat/64.png",
            code: "+592",
            display: "+592 (Guyana)",
          },
          {
            id: 90,
            flag: "https://www.countryflags.io/ht/flat/64.png",
            code: "+509",
            display: "+509 (Haiti)",
          },
          {
            id: 91,
            flag: "https://www.countryflags.io/hn/flat/64.png",
            code: "+504",
            display: "+504 (Honduras)",
          },
          {
            id: 92,
            flag: "https://www.countryflags.io/hk/flat/64.png",
            code: "+852",
            display: "+852 (Hong Kong)",
          },
          {
            id: 93,
            flag: "https://www.countryflags.io/hu/flat/64.png",
            code: "+36",
            display: "+36 (Hungary)",
          },
          {
            id: 94,
            flag: "https://www.countryflags.io/is/flat/64.png",
            code: "+354",
            display: "+354 (Iceland)",
          },
          {
            id: 95,
            flag: "https://www.countryflags.io/in/flat/64.png",
            code: "+91",
            display: "+91 (India)",
          },
          {
            id: 96,
            flag: "https://www.countryflags.io/id/flat/64.png",
            code: "+62",
            display: "+62 (Indonesia)",
          },
          {
            id: 97,
            flag: "https://www.countryflags.io/ir/flat/64.png",
            code: "+98",
            display: "+98 (Iran)",
          },
          {
            id: 98,
            flag: "https://www.countryflags.io/iq/flat/64.png",
            code: "+964",
            display: "+964 (Iraq)",
          },
          {
            id: 99,
            flag: "https://www.countryflags.io/ie/flat/64.png",
            code: "+353",
            display: "+353 (Ireland)",
          },
          {
            id: 100,
            flag: "https://www.countryflags.io/im/flat/64.png",
            code: "+441624",
            display: "+441624 (Isle of Man)",
          },
          {
            id: 101,
            flag: "https://www.countryflags.io/il/flat/64.png",
            code: "+972",
            display: "+972 (Israel)",
          },
          {
            id: 102,
            flag: "https://www.countryflags.io/it/flat/64.png",
            code: "+39",
            display: "+39 (Italy)",
          },
          {
            id: 103,
            flag: "https://www.countryflags.io/ci/flat/64.png",
            code: "+225",
            display: "+225 (Ivory Coast)",
          },
          {
            id: 104,
            flag: "https://www.countryflags.io/jm/flat/64.png",
            code: "+1876",
            display: "+1876 (Jamaica)",
          },
          {
            id: 105,
            flag: "https://www.countryflags.io/jp/flat/64.png",
            code: "+81",
            display: "+81 (Japan)",
          },
          {
            id: 106,
            flag: "https://www.countryflags.io/je/flat/64.png",
            code: "+441534",
            display: "+441534 (Jersey)",
          },
          {
            id: 107,
            flag: "https://www.countryflags.io/jo/flat/64.png",
            code: "+962",
            display: "+962 (Jordan)",
          },
          {
            id: 108,
            flag: "https://www.countryflags.io/kz/flat/64.png",
            code: "+7",
            display: "+7 (Kazakhstan)",
          },
          {
            id: 109,
            flag: "https://www.countryflags.io/ke/flat/64.png",
            code: "+254",
            display: "+254 (Kenya)",
          },
          {
            id: 110,
            flag: "https://www.countryflags.io/ki/flat/64.png",
            code: "+686",
            display: "+686 (Kiribati)",
          },
          {
            id: 111,
            flag: "https://www.countryflags.io/xk/flat/64.png",
            code: "+383",
            display: "+383 (Kosovo)",
          },
          {
            id: 112,
            flag: "https://www.countryflags.io/kw/flat/64.png",
            code: "+965",
            display: "+965 (Kuwait)",
          },
          {
            id: 113,
            flag: "https://www.countryflags.io/kg/flat/64.png",
            code: "+996",
            display: "+996 (Kyrgyzstan)",
          },
          {
            id: 114,
            flag: "https://www.countryflags.io/la/flat/64.png",
            code: "+856",
            display: "+856 (Laos)",
          },
          {
            id: 115,
            flag: "https://www.countryflags.io/lv/flat/64.png",
            code: "+371",
            display: "+371 (Latvia)",
          },
          {
            id: 116,
            flag: "https://www.countryflags.io/lb/flat/64.png",
            code: "+961",
            display: "+961 (Lebanon)",
          },
          {
            id: 117,
            flag: "https://www.countryflags.io/ls/flat/64.png",
            code: "+266",
            display: "+266 (Lesotho)",
          },
          {
            id: 118,
            flag: "https://www.countryflags.io/lr/flat/64.png",
            code: "+231",
            display: "+231 (Liberia)",
          },
          {
            id: 119,
            flag: "https://www.countryflags.io/ly/flat/64.png",
            code: "+218",
            display: "+218 (Libya)",
          },
          {
            id: 120,
            flag: "https://www.countryflags.io/li/flat/64.png",
            code: "+423",
            display: "+423 (Liechtenstein)",
          },
          {
            id: 121,
            flag: "https://www.countryflags.io/lt/flat/64.png",
            code: "+370",
            display: "+370 (Lithuania)",
          },
          {
            id: 122,
            flag: "https://www.countryflags.io/lu/flat/64.png",
            code: "+352",
            display: "+352 (Luxembourg)",
          },
          {
            id: 123,
            flag: "https://www.countryflags.io/mo/flat/64.png",
            code: "+853",
            display: "+853 (Macau)",
          },
          {
            id: 124,
            flag: "https://www.countryflags.io/mk/flat/64.png",
            code: "+389",
            display: "+389 (Macedonia)",
          },
          {
            id: 125,
            flag: "https://www.countryflags.io/mg/flat/64.png",
            code: "+261",
            display: "+261 (Madagascar)",
          },
          {
            id: 126,
            flag: "https://www.countryflags.io/mw/flat/64.png",
            code: "+265",
            display: "+265 (Malawi)",
          },
          {
            id: 127,
            flag: "https://www.countryflags.io/my/flat/64.png",
            code: "+60",
            display: "+60 (Malaysia)",
          },
          {
            id: 128,
            flag: "https://www.countryflags.io/mv/flat/64.png",
            code: "+960",
            display: "+960 (Maldives)",
          },
          {
            id: 129,
            flag: "https://www.countryflags.io/ml/flat/64.png",
            code: "+223",
            display: "+223 (Mali)",
          },
          {
            id: 130,
            flag: "https://www.countryflags.io/mt/flat/64.png",
            code: "+356",
            display: "+356 (Malta)",
          },
          {
            id: 131,
            flag: "https://www.countryflags.io/mh/flat/64.png",
            code: "+692",
            display: "+692 (Marshall Islands)",
          },
          {
            id: 132,
            flag: "https://www.countryflags.io/mr/flat/64.png",
            code: "+222",
            display: "+222 (Mauritania)",
          },
          {
            id: 133,
            flag: "https://www.countryflags.io/mu/flat/64.png",
            code: "+230",
            display: "+230 (Mauritius)",
          },
          {
            id: 134,
            flag: "https://www.countryflags.io/yt/flat/64.png",
            code: "+262",
            display: "+262 (Mayotte)",
          },
          {
            id: 135,
            flag: "https://www.countryflags.io/mx/flat/64.png",
            code: "+52",
            display: "+52 (Mexico)",
          },
          {
            id: 136,
            flag: "https://www.countryflags.io/fm/flat/64.png",
            code: "+691",
            display: "+691 (Micronesia)",
          },
          {
            id: 137,
            flag: "https://www.countryflags.io/md/flat/64.png",
            code: "+373",
            display: "+373 (Moldova)",
          },
          {
            id: 138,
            flag: "https://www.countryflags.io/mc/flat/64.png",
            code: "+377",
            display: "+377 (Monaco)",
          },
          {
            id: 139,
            flag: "https://www.countryflags.io/mn/flat/64.png",
            code: "+976",
            display: "+976 (Mongolia)",
          },
          {
            id: 140,
            flag: "https://www.countryflags.io/me/flat/64.png",
            code: "+382",
            display: "+382 (Montenegro)",
          },
          {
            id: 141,
            flag: "https://www.countryflags.io/ms/flat/64.png",
            code: "+1664",
            display: "+1664 (Montserrat)",
          },
          {
            id: 142,
            flag: "https://www.countryflags.io/ma/flat/64.png",
            code: "+212",
            display: "+212 (Morocco)",
          },
          {
            id: 143,
            flag: "https://www.countryflags.io/mz/flat/64.png",
            code: "+258",
            display: "+258 (Mozambique)",
          },
          {
            id: 144,
            flag: "https://www.countryflags.io/mm/flat/64.png",
            code: "+95",
            display: "+95 (Myanmar)",
          },
          {
            id: 145,
            flag: "https://www.countryflags.io/na/flat/64.png",
            code: "+264",
            display: "+264 (Namibia)",
          },
          {
            id: 146,
            flag: "https://www.countryflags.io/nr/flat/64.png",
            code: "+674",
            display: "+674 (Nauru)",
          },
          {
            id: 147,
            flag: "https://www.countryflags.io/np/flat/64.png",
            code: "+977",
            display: "+977 (Nepal)",
          },
          {
            id: 148,
            flag: "https://www.countryflags.io/nl/flat/64.png",
            code: "+31",
            display: "+31 (Netherlands)",
          },
          {
            id: 149,
            flag: "https://www.countryflags.io/an/flat/64.png",
            code: "+599",
            display: "+599 (Netherlands Antilles)",
          },
          {
            id: 150,
            flag: "https://www.countryflags.io/nc/flat/64.png",
            code: "+687",
            display: "+687 (New Caledonia)",
          },
          {
            id: 151,
            flag: "https://www.countryflags.io/nz/flat/64.png",
            code: "+64",
            display: "+64 (New Zealand)",
          },
          {
            id: 152,
            flag: "https://www.countryflags.io/ni/flat/64.png",
            code: "+505",
            display: "+505 (Nicaragua)",
          },
          {
            id: 153,
            flag: "https://www.countryflags.io/ne/flat/64.png",
            code: "+227",
            display: "+227 (Niger)",
          },
          {
            id: 154,
            flag: "https://www.countryflags.io/ng/flat/64.png",
            code: "+234",
            display: "+234 (Nigeria)",
          },
          {
            id: 155,
            flag: "https://www.countryflags.io/nu/flat/64.png",
            code: "+683",
            display: "+683 (Niue)",
          },
          {
            id: 156,
            flag: "https://www.countryflags.io/kp/flat/64.png",
            code: "+850",
            display: "+850 (North Korea)",
          },
          {
            id: 157,
            flag: "https://www.countryflags.io/mp/flat/64.png",
            code: "+1670",
            display: "+1670 (Northern Mariana Islands)",
          },
          {
            id: 158,
            flag: "https://www.countryflags.io/no/flat/64.png",
            code: "+47",
            display: "+47 (Norway)",
          },
          {
            id: 159,
            flag: "https://www.countryflags.io/om/flat/64.png",
            code: "+968",
            display: "+968 (Oman)",
          },
          {
            id: 160,
            flag: "https://www.countryflags.io/pk/flat/64.png",
            code: "+92",
            display: "+92 (Pakistan)",
          },
          {
            id: 161,
            flag: "https://www.countryflags.io/pw/flat/64.png",
            code: "+680",
            display: "+680 (Palau)",
          },
          {
            id: 162,
            flag: "https://www.countryflags.io/ps/flat/64.png",
            code: "+970",
            display: "+970 (Palestine)",
          },
          {
            id: 163,
            flag: "https://www.countryflags.io/pa/flat/64.png",
            code: "+507",
            display: "+507 (Panama)",
          },
          {
            id: 164,
            flag: "https://www.countryflags.io/pg/flat/64.png",
            code: "+675",
            display: "+675 (Papua New Guinea)",
          },
          {
            id: 165,
            flag: "https://www.countryflags.io/py/flat/64.png",
            code: "+595",
            display: "+595 (Paraguay)",
          },
          {
            id: 166,
            flag: "https://www.countryflags.io/pe/flat/64.png",
            code: "+51",
            display: "+51 (Peru)",
          },
          {
            id: 167,
            flag: "https://www.countryflags.io/ph/flat/64.png",
            code: "+63",
            display: "+63 (Philippines)",
          },
          {
            id: 168,
            flag: "https://www.countryflags.io/pn/flat/64.png",
            code: "+64",
            display: "+64 (Pitcairn)",
          },
          {
            id: 169,
            flag: "https://www.countryflags.io/pl/flat/64.png",
            code: "+48",
            display: "+48 (Poland)",
          },
          {
            id: 170,
            flag: "https://www.countryflags.io/pt/flat/64.png",
            code: "+351",
            display: "+351 (Portugal)",
          },
          {
            id: 171,
            flag: "https://www.countryflags.io/pr/flat/64.png",
            code: "+1787, 1939",
            display: "+1787, 1939 (Puerto Rico)",
          },
          {
            id: 172,
            flag: "https://www.countryflags.io/qa/flat/64.png",
            code: "+974",
            display: "+974 (Qatar)",
          },
          {
            id: 173,
            flag: "https://www.countryflags.io/cg/flat/64.png",
            code: "+242",
            display: "+242 (Republic of the Congo)",
          },
          {
            id: 174,
            flag: "https://www.countryflags.io/re/flat/64.png",
            code: "+262",
            display: "+262 (Reunion)",
          },
          {
            id: 175,
            flag: "https://www.countryflags.io/ro/flat/64.png",
            code: "+40",
            display: "+40 (Romania)",
          },
          {
            id: 176,
            flag: "https://www.countryflags.io/ru/flat/64.png",
            code: "+7",
            display: "+7 (Russia)",
          },
          {
            id: 177,
            flag: "https://www.countryflags.io/rw/flat/64.png",
            code: "+250",
            display: "+250 (Rwanda)",
          },
          {
            id: 178,
            flag: "https://www.countryflags.io/bl/flat/64.png",
            code: "+590",
            display: "+590 (Saint Barthelemy)",
          },
          {
            id: 179,
            flag: "https://www.countryflags.io/sh/flat/64.png",
            code: "+290",
            display: "+290 (Saint Helena)",
          },
          {
            id: 180,
            flag: "https://www.countryflags.io/kn/flat/64.png",
            code: "+1869",
            display: "+1869 (Saint Kitts and Nevis)",
          },
          {
            id: 181,
            flag: "https://www.countryflags.io/lc/flat/64.png",
            code: "+1758",
            display: "+1758 (Saint Lucia)",
          },
          {
            id: 182,
            flag: "https://www.countryflags.io/mf/flat/64.png",
            code: "+590",
            display: "+590 (Saint Martin)",
          },
          {
            id: 183,
            flag: "https://www.countryflags.io/pm/flat/64.png",
            code: "+508",
            display: "+508 (Saint Pierre and Miquelon)",
          },
          {
            id: 184,
            flag: "https://www.countryflags.io/vc/flat/64.png",
            code: "+1784",
            display: "+1784 (Saint Vincent and the Grenadines)",
          },
          {
            id: 185,
            flag: "https://www.countryflags.io/ws/flat/64.png",
            code: "+685",
            display: "+685 (Samoa)",
          },
          {
            id: 186,
            flag: "https://www.countryflags.io/sm/flat/64.png",
            code: "+378",
            display: "+378 (San Marino)",
          },
          {
            id: 187,
            flag: "https://www.countryflags.io/st/flat/64.png",
            code: "+239",
            display: "+239 (Sao Tome and Principe)",
          },
          {
            id: 188,
            flag: "https://www.countryflags.io/sa/flat/64.png",
            code: "+966",
            display: "+966 (Saudi Arabia)",
          },
          {
            id: 189,
            flag: "https://www.countryflags.io/sn/flat/64.png",
            code: "+221",
            display: "+221 (Senegal)",
          },
          {
            id: 190,
            flag: "https://www.countryflags.io/rs/flat/64.png",
            code: "+381",
            display: "+381 (Serbia)",
          },
          {
            id: 191,
            flag: "https://www.countryflags.io/sc/flat/64.png",
            code: "+248",
            display: "+248 (Seychelles)",
          },
          {
            id: 192,
            flag: "https://www.countryflags.io/sl/flat/64.png",
            code: "+232",
            display: "+232 (Sierra Leone)",
          },
          {
            id: 193,
            flag: "https://www.countryflags.io/sg/flat/64.png",
            code: "+65",
            display: "+65 (Singapore)",
          },
          {
            id: 194,
            flag: "https://www.countryflags.io/sx/flat/64.png",
            code: "+1721",
            display: "+1721 (Sint Maarten)",
          },
          {
            id: 195,
            flag: "https://www.countryflags.io/sk/flat/64.png",
            code: "+421",
            display: "+421 (Slovakia)",
          },
          {
            id: 196,
            flag: "https://www.countryflags.io/si/flat/64.png",
            code: "+386",
            display: "+386 (Slovenia)",
          },
          {
            id: 197,
            flag: "https://www.countryflags.io/sb/flat/64.png",
            code: "+677",
            display: "+677 (Solomon Islands)",
          },
          {
            id: 198,
            flag: "https://www.countryflags.io/so/flat/64.png",
            code: "+252",
            display: "+252 (Somalia)",
          },
          {
            id: 199,
            flag: "https://www.countryflags.io/za/flat/64.png",
            code: "+27",
            display: "+27 (South Africa)",
          },
          {
            id: 200,
            flag: "https://www.countryflags.io/kr/flat/64.png",
            code: "+82",
            display: "+82 (South Korea)",
          },
          {
            id: 201,
            flag: "https://www.countryflags.io/ss/flat/64.png",
            code: "+211",
            display: "+211 (South Sudan)",
          },
          {
            id: 202,
            flag: "https://www.countryflags.io/es/flat/64.png",
            code: "+34",
            display: "+34 (Spain)",
          },
          {
            id: 203,
            flag: "https://www.countryflags.io/lk/flat/64.png",
            code: "+94",
            display: "+94 (Sri Lanka)",
          },
          {
            id: 204,
            flag: "https://www.countryflags.io/sd/flat/64.png",
            code: "+249",
            display: "+249 (Sudan)",
          },
          {
            id: 205,
            flag: "https://www.countryflags.io/sr/flat/64.png",
            code: "+597",
            display: "+597 (Suriname)",
          },
          {
            id: 206,
            flag: "https://www.countryflags.io/sj/flat/64.png",
            code: "+47",
            display: "+47 (Svalbard and Jan Mayen)",
          },
          {
            id: 207,
            flag: "https://www.countryflags.io/sz/flat/64.png",
            code: "+268",
            display: "+268 (Swaziland)",
          },
          {
            id: 208,
            flag: "https://www.countryflags.io/se/flat/64.png",
            code: "+46",
            display: "+46 (Sweden)",
          },
          {
            id: 209,
            flag: "https://www.countryflags.io/ch/flat/64.png",
            code: "+41",
            display: "+41 (Switzerland)",
          },
          {
            id: 210,
            flag: "https://www.countryflags.io/sy/flat/64.png",
            code: "+963",
            display: "+963 (Syria)",
          },
          {
            id: 211,
            flag: "https://www.countryflags.io/tw/flat/64.png",
            code: "+886",
            display: "+886 (Taiwan)",
          },
          {
            id: 212,
            flag: "https://www.countryflags.io/tj/flat/64.png",
            code: "+992",
            display: "+992 (Tajikistan)",
          },
          {
            id: 213,
            flag: "https://www.countryflags.io/tz/flat/64.png",
            code: "+255",
            display: "+255 (Tanzania)",
          },
          {
            id: 214,
            flag: "https://www.countryflags.io/th/flat/64.png",
            code: "+66",
            display: "+66 (Thailand)",
          },
          {
            id: 215,
            flag: "https://www.countryflags.io/tg/flat/64.png",
            code: "+228",
            display: "+228 (Togo)",
          },
          {
            id: 216,
            flag: "https://www.countryflags.io/tk/flat/64.png",
            code: "+690",
            display: "+690 (Tokelau)",
          },
          {
            id: 217,
            flag: "https://www.countryflags.io/to/flat/64.png",
            code: "+676",
            display: "+676 (Tonga)",
          },
          {
            id: 218,
            flag: "https://www.countryflags.io/tt/flat/64.png",
            code: "+1868",
            display: "+1868 (Trinidad and Tobago)",
          },
          {
            id: 219,
            flag: "https://www.countryflags.io/tn/flat/64.png",
            code: "+216",
            display: "+216 (Tunisia)",
          },
          {
            id: 220,
            flag: "https://www.countryflags.io/tr/flat/64.png",
            code: "+90",
            display: "+90 (Turkey)",
          },
          {
            id: 221,
            flag: "https://www.countryflags.io/tm/flat/64.png",
            code: "+993",
            display: "+993 (Turkmenistan)",
          },
          {
            id: 222,
            flag: "https://www.countryflags.io/tc/flat/64.png",
            code: "+1649",
            display: "+1649 (Turks and Caicos Islands)",
          },
          {
            id: 223,
            flag: "https://www.countryflags.io/tv/flat/64.png",
            code: "+688",
            display: "+688 (Tuvalu)",
          },
          {
            id: 224,
            flag: "https://www.countryflags.io/vi/flat/64.png",
            code: "+1340",
            display: "+1340 (U.S. Virgin Islands)",
          },
          {
            id: 225,
            flag: "https://www.countryflags.io/ug/flat/64.png",
            code: "+256",
            display: "+256 (Uganda)",
          },
          {
            id: 226,
            flag: "https://www.countryflags.io/ua/flat/64.png",
            code: "+380",
            display: "+380 (Ukraine)",
          },
          {
            id: 227,
            flag: "https://www.countryflags.io/ae/flat/64.png",
            code: "+971",
            display: "+971 (United Arab Emirates)",
          },
          {
            id: 228,
            flag: "https://www.countryflags.io/gb/flat/64.png",
            code: "+44",
            display: "+44 (United Kingdom)",
          },
          {
            id: 229,
            flag: "https://www.countryflags.io/us/flat/64.png",
            code: "+1",
            display: "+1 (United States)",
          },
          {
            id: 230,
            flag: "https://www.countryflags.io/uy/flat/64.png",
            code: "+598",
            display: "+598 (Uruguay)",
          },
          {
            id: 231,
            flag: "https://www.countryflags.io/uz/flat/64.png",
            code: "+998",
            display: "+998 (Uzbekistan)",
          },
          {
            id: 232,
            flag: "https://www.countryflags.io/vu/flat/64.png",
            code: "+678",
            display: "+678 (Vanuatu)",
          },
          {
            id: 233,
            flag: "https://www.countryflags.io/va/flat/64.png",
            code: "+379",
            display: "+379 (Vatican)",
          },
          {
            id: 234,
            flag: "https://www.countryflags.io/ve/flat/64.png",
            code: "+58",
            display: "+58 (Venezuela)",
          },
          {
            id: 235,
            flag: "https://www.countryflags.io/vn/flat/64.png",
            code: "+84",
            display: "+84 (Vietnam)",
          },
          {
            id: 236,
            flag: "https://www.countryflags.io/wf/flat/64.png",
            code: "+681",
            display: "+681 (Wallis and Futuna)",
          },
          {
            id: 237,
            flag: "https://www.countryflags.io/eh/flat/64.png",
            code: "+212",
            display: "+212 (Western Sahara)",
          },
          {
            id: 238,
            flag: "https://www.countryflags.io/ye/flat/64.png",
            code: "+967",
            display: "+967 (Yemen)",
          },
          {
            id: 239,
            flag: "https://www.countryflags.io/zm/flat/64.png",
            code: "+260",
            display: "+260 (Zambia)",
          },
          {
            id: 240,
            flag: "https://www.countryflags.io/zw/flat/64.png",
            code: "+263",
            display: "+263 (Zimbabwe)",
          },
        ],
      });
    });
  }
}

export default new StaticDataService();
