//List Actions
export const FETCH_LISTDEMO_BEGIN = "FETCH_LISTDEMO_BEGIN";
export const FETCH_LISTDEMO_SUCCESS = "FETCH_LISTDEMO_SUCCESS";
export const FETCH_LISTDEMO_FAILURE = "FETCH_LISTDEMO_FAILURE";
//Other Actions...
